export const colors = {
  bg: "#FBFCF9",
  surface: "#FFFFFF",
  surfaceTint: "#F5FAF6",
  surfaceInset: "#EAF3EC",
  border: "#D5E8DA",
  borderStrong: "#C0D9C7",
  primary: "#0D6B3A",
  primaryDeep: "#0A4D2C",
  primaryMid: "#1A9151",
  primaryFresh: "#2DB870",
  primaryPale: "#E6F7EE",
  fundBlue: "#2A4FA8",
  fundBluePale: "#EEF2FC",
  fundBlueBorder: "#B6C8EF",
  text: "#0D1F14",
  textMuted: "#4A6B55",
  textSubtle: "#8DAB97",
  white: "#FFFFFF",
  danger: "#C73B3B",
  dangerPale: "#FBECEC",
  warning: "#D88A2C",
  warningPale: "#FBF1DC",
};
